### ISSUE TITLE
can not install plugin

### ISSUE THREAD

**Issue by rolfkokkeler** [lindseydiloreto/craft-cpcss#10]
how do I install the plugin?
Do I rename the folder? 
I can not see the plugin in my settings

**Comment by lindseydiloreto** [comment]
If you are in **Craft 3**, then you can just download it for free via the "Plugin Store" link in your control panel.

If you are in **Craft 2**, make sure you have downloaded the [`v1` branch](https://github.com/doublesecretagency/craft-cpcss/tree/v1). The `cpcss` folder is what you will move into your `plugins` folder, so the final structure in your site will look like this:

    /plugins/cpcss

**Comment by rolfkokkeler** [comment]
thanx, we tried to install the v2 branch in Craft 2...

**Comment by lindseydiloreto** [comment]
Gotcha, that's what I figured. I may add a note to the README to prevent confusion. 👍
