### ISSUE TITLE
Craft 3 or 2?

### ISSUE THREAD

**Issue by DZuz14** [lindseydiloreto/craft-cpcss#11]
How do I actually install this? Unzipped and put in Craft 2 plugins folder and nothing shows up.

**Comment by DZuz14** [comment]
Fixed it by using v1 branch. However, may I suggest putting this in very apparent fashion almost towards the top of the Github page under something like "Installation"? Prob will get more installs of this if people don't have to go through the hassle.

Its not a huge hassle, but some people might just give up immediately once they drag it in, and realize it doesnt work.

**Comment by lindseydiloreto** [comment]
Thanks for letting me know (you actually weren't the first person to get confused by this).

I've added a message to both branches in order to clarify. Hope that helps!
