### ISSUE TITLE
Failed to install cp-css

### ISSUE THREAD

**Issue by richhayler** [lindseydiloreto/craft-cpcss#13]
Trying to install **cp-css** from the command line and getting the error "No plugin exists with the handle cp-css"
I have repeated the same steps for cp-js and it works as expected.

```
composer require doublesecretagency/craft-cpcss
./craft plugin/install cp-css
*** installing cp-css
*** failed to install cp-css: No plugin exists with the handle "cp-css".


composer require doublesecretagency/craft-cpjs
./craft plugin/install cp-js
*** installing cp-js
*** installed cp-js successfully (time: 0.034s)
```

**CraftCMS**: 3.5.13.2
**PHP** 7.4
**Ubuntu**: 20.04

**Comment by richhayler** [comment]
I rebuilt project config and this solved my issue.

**Comment by lindseydiloreto** [comment]
Ok cool, glad you got it sorted out! 👍
