### ISSUE TITLE
FR - Multiple CSS files

### ISSUE THREAD

**Issue by wmdhosting** [lindseydiloreto/craft-cpcss#14]
Hello Lindsey :)

Any chance to add support to edit more than 1 css files. 

Table for settings will do whats needed

**Comment by lindseydiloreto** [comment]
Hi there!

Correct me if I'm wrong, it sounds like you want to be able to reference multiple external CSS files?

Someone recently filed a similar pull request on the CP JS plugin (which largely mirrors CP CSS). Does this pull request more or less describe the behavior that you are looking for here?

 - https://github.com/doublesecretagency/craft-cpjs/pull/3

I try to maintain parity between the CP CSS and CP JS plugins. If the pull request described there is similar to what you are asking for, then I will...

 1. accept the PR for the CP JS plugin, and
 2. copy the identical functionality over to CP CSS.

Does that align with what you need?

**Comment by wmdhosting** [comment]
thx for fast response..  :)

Yes :)

**Comment by lindseydiloreto** [comment]
Done and done. This is now possible in **v2.3**. 👍
