### ISSUE TITLE
URL vs path & CP warning

### ISSUE THREAD

**Issue by heymarkreeves** [lindseydiloreto/craft-cpcss#15]
CP CSS is installed in a site I've taken over, where the setting for CSS file contains:

```
@web/assets/css/cp.css
```

Using `./craft serve`, I get the following:

```
2021-11-11 21:12:29 [-][1765][-][warning][application] Can't bust cache of CP CSS, unable to load contents of http://localhost:8080/assets/css/cp.css
```

I can fix that by setting `'cacheBusting' => false`. The file exists, and if I disable cache busting, I can see it applied in the control panel. But I can't use the control panel because every screen takes 2 minutes to try to load that.

I'm guessing this is because the built-in PHP server is single-threaded, and it times out waiting for `file_get_contents` to respond.

Isn't `_addHash` just adding a querystring param? Does the file actually need to be loaded from its URL?

**Comment by lindseydiloreto** [comment]
> Isn't `_addHash` just adding a querystring param? Does the file actually need to be loaded from its URL?

The CSS file must be loaded, because a unique hash is generated based on the content of the file. So the cache won't get busted until the file contents change.

In rare edge cases, this seems to cause problems, which is why we added the `cacheBusting` config option. You may be right about single-threaded PHP, I never quite figured out what was causing the system to hang.

Which of these warning messages is showing up in your logs?

- https://github.com/doublesecretagency/craft-cpcss/blob/v2/src/web/assets/CustomAssets.php#L87
- https://github.com/doublesecretagency/craft-cpcss/blob/v2/src/web/assets/CustomAssets.php#L98

**Comment by heymarkreeves** [comment]
Ah, gotcha. Changed contents = new hash vs old hash. You don't want it on every load.

It's the line 87 message. It's definitely the single threaded timeout. I've run into the same sort of issue with Twigpack, when it's trying to fetch the manifest from the same URL it's running on.

**Comment by lindseydiloreto** [comment]
Sounds similar. Do you have a workaround for Twigpack? Or do you just disable this type of behavior?

**Comment by heymarkreeves** [comment]
I gave up on `./craft serve` and installed Laravel Valet :)

**Comment by lindseydiloreto** [comment]
Ha, sounds good to me. 😄

**Comment by gorelegacy** [comment]
Im getting this warning every page load in the admin @lindseydiloreto 

`Can't bust cache of CP CSS, unable to load contents of /built/css/admin.css`

and in my inspector

`<link href="/built/css/admin.css?v=1731633866" rel="stylesheet">` and link works and opens the stylesheet

Yet my files are hashed when i inspect and the JS & CSS files are working in the admin. So why am i getting warnings?

Both JS & CSS on 2.6.0
Craft 4.12.9

**Comment by romainpoirier** [comment]
I am experiencing the same issue. My files are accessible, yet I am receiving a significant number of warnings. Setting `cacheBusting` to `false` is not a proper solution. How can I resolve this? I am encountering the exact same problem with your other plugin, cpjs.

Here’s my configuration:

- `craftcms/cms`: `5.6.13`
- `doublesecretagency/craft-cpcss`: `^3.0.0`
- `doublesecretagency/craft-cpjs`: `^3.0.0`
