### ISSUE TITLE
Installation failed on Craft 3.7.43

### ISSUE THREAD

**Issue by dragan1700** [lindseydiloreto/craft-cpcss#18]
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doublesecretagency/craft-cpcss ^2.5 -> satisfiable by doublesecretagency/craft-cpcss[2.5.0].
    - doublesecretagency/craft-cpcss 2.5.0 requires craftcms/cms ^4.0.0-beta -> satisfiable by craftcms/cms[4.0.0, 4.0.0-RC1, 4.0.0-RC2, 4.0.0-RC3, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.0.1, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.5.1, 4.0.5.2, 4.0.6, 4.1.0, 4.1.0.1, 4.1.0.2, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.x-dev, 4.2.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.`

According to https://plugins.craftcms.com/cp-css it should be compatible with Craft 3 as well though...

**Comment by lindseydiloreto** [comment]
Looks like you're trying to install the Craft 4 version of CP CSS (v2.5). The last Craft 3 compatible version is CP CSS **v2.4.0**.

Try lowering your composer requirements to `^2.4`. And if that doesn't work, you can lock it in as `2.4` exactly.

```
"doublesecretagency/craft-cpcss": "2.4"
```
