### ISSUE TITLE
Feature Request: Allow twig code in cssFile settings

### ISSUE THREAD

**Issue by webrgp** [lindseydiloreto/craft-cpcss#19]
I am using Vite to compile my css, and the output is name.xxxxx.css

By allowing Twig in the field, I could use Andrew's Vite plugin and enter `{{ craft.vite.entry('name.css') }}` which would grab the correct file path from the manifest.

**Comment by khalwat** [comment]
@webrgp you could also generate your output file names without the hashes if you wanted to:

```js
rollupOutputOptions: {
    entryFileNames: `[name].js`,
    chunkFileNames: `[name].js`,
    assetFileNames: `[name].[ext]`
}
```

ref: https://vitejs.dev/config/build-options.html#build-rollupoptions

**Comment by webrgp** [comment]
Thanks Andrew!
