### ISSUE TITLE
Plugin Page 404

### ISSUE THREAD

**Issue by mark-chief** [lindseydiloreto/craft-cpcss#21]
Hello, all of a sudden the CP CSS page is showing a 404.

I've removed the plugin and re-installed with no joy..

<img width="1400" alt="Screenshot 2023-03-23 at 16 45 42" src="https://user-images.githubusercontent.com/18699249/227275833-6444f7b7-efb3-4586-a1ad-8bb0e659d3b1.png">

<img width="794" alt="Screenshot 2023-03-23 at 16 48 43" src="https://user-images.githubusercontent.com/18699249/227276152-a6483646-65b6-4d8f-bba7-d1d3e27f8dd2.png">

Craft: 3.7.65.2
CP CSS: 2.4.0

Thanks

**Comment by lindseydiloreto** [comment]
I'm assuming by the self-close that you were able to sort it out. 🙂
