### ISSUE TITLE
Per member group

### ISSUE THREAD

**Issue by jacobgraf** [lindseydiloreto/craft-cpcss#4]
First off, thanks for writing the Control Panel CSS plugin. One thing I thought of was that it would be cool if you could define custom CSS on a per member group basis. Not sure what's involved technically with this but would be awesome for a number of things.

**Comment by lindseydiloreto** [comment]
@jacobgraf Digging up this old thread... I've decided to make a formal feature request to solve multiple problems at once...

http://feedback.buildwithcraft.com/forums/285221-feature-requests/suggestions/7900728-circumstantial-cp-body-classes

**Comment by jordanlev** [comment]
:+1:

**Comment by lindseydiloreto** [comment]
Looks like the feature request got vetoed... so I made a custom plugin for it instead...

https://github.com/lindseydiloreto/craft-cpusergroup

That plugin will add user group classes to the `<body>` tag automatically. You can then use CP CSS to target each group individual, and customize your CP differently for each group!

**Comment by jacobgraf** [comment]
Awesome! Thanks Lindsey!
