### ISSUE TITLE
Redirect to same route on Save?

### ISSUE THREAD

**Issue by miralize** [lindseydiloreto/craft-cpcss#6]
I'm spoiled by CSS preprocessors, would it be possible, if on save, there was an option to redirect you back to the editor screen. It would make debugging small header changes incredibly easy!

**Comment by lindseydiloreto** [comment]
That's interesting, I'll have to take a look into that.

Since it's being saved on the Settings page, it's following some logic dictated by default settings behavior (which is a little stricter than other custom pages). But if I can pull it off, I'd be happy to make that change!

**Comment by lindseydiloreto** [comment]
Been thinking about how to pull this off for awhile now, and I can't really think of a non-hacky way to do it. So I opened a feature request...

[Plugin Settings - "Save & Continue Editing"](http://feedback.buildwithcraft.com/forums/285221-feature-requests/suggestions/11179854-plugin-settings-save-continue-editing)

Please cast your vote there!

**Comment by lindseydiloreto** [comment]
@miralize: Your wish has been granted, courtesy of @mmikkel!

He just submitted a pull request which does exactly what you're looking for. The "Save" button now includes a "Save & Continue" option... additionally, the keyboard shortcut for saving will keep you on the same page. :+1:
