### ISSUE TITLE
problem with thumbnail elements

### ISSUE THREAD

**Issue by AgnieszkaCE** [lindseydiloreto/craft-cpcss#9]
As shown on the screenshot, I have a problem with thumbnail elements in models forms. The label overlaps the element below. I have found that the problem is caused by fixed height of  .element class.
![movie-title](https://user-images.githubusercontent.com/6688682/27123177-57a32e28-50ed-11e7-8715-b09a7f73027b.png)

**Comment by lindseydiloreto** [comment]
Sorry, we can't lend assistance with your own custom CSS. This plugin only provides you the _capability_ to override the Control Panel CSS, it doesn't dictate what you do with that power.

If you're trying to report a bug with the native CSS in Craft, you'll want to post on the [Craft CMS repo](https://github.com/craftcms/cms/issues) instead.
